fun main(){
    print("Enter Enrollment number : ")
    var a = readLine()!!.toLong()
    print("Enter Name : ")
    var b = readLine()
    print("Enter Branch : ")
    var c = readLine()
    print("Enter Class : ")
    var d = readLine()
    print("Enter Batch : ")
    var e = readLine()
    print("Enter College Name : ")
    var f = readLine()
    print("Enter University Name : ")
    var g = readLine()
    print("Enter Age : ")
    var h = readLine()!!.toInt()

    println("**************")
    println("Student Enrollment No. :  $a")
    println("Student Name :  $b")
    println("Student Branch :  $c")
    println("Student Class :  $d")
    println("Student Batch :  $e")
    println("Student College Name :  $f")
    println("Student University Name :  $g")
    println("Student Age :  $h")

}